# Generated by Django 6.0.1 on 2026-01-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('utility', 'Utility'), ('supplies', 'Supplies'), ('maintenance', 'Maintenance'), ('amenities', 'Amenities')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateField()),
                ('paid_to', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'school_expenditures',
            },
        ),
    ]
