# Generated by Django 6.0.1 on 2026-01-17 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('health_info', models.TextField(blank=True)),
                ('staff_type', models.CharField(choices=[('teaching', 'Teaching'), ('non-teaching', 'Non Teaching')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'staff details',
                'db_table': 'staff_details',
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave')], max_length=10)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.staffdetails')),
            ],
            options={
                'db_table': 'staff_attendance',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly')], max_length=10)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='hr.staffdetails')),
            ],
            options={
                'verbose_name_plural': 'salaries',
                'db_table': 'salaries',
            },
        ),
    ]
